eureka:
  instance:
    prefer-ip-address: true              # en local, plus simple
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}   # 👈 Eureka sur ta machine

name:
  value: dodashx

spring:
  cloud:
    config:
      override-system-properties: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING:1.0}
  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    endpoint: ${ZIPKIN_ENDPOINT:http://localhost:${ZIPKIN_PORT:9411}/api/v2/spans}     # 👈 Zipkin local
