eureka:
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:${SPRING_APPLICATION_NAME}}   # ← prend le nom du conteneur si possible
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service:8761/eureka}
name:
  value: dodashx
spring:
  cloud:
    config:
      override-system-properties: false


management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING:1.0}
      zipkin:
        enabled: ${ZIPKIN_ENABLED:true}
        endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}

