# --- DEV profile overrides ---
server:
  port: ${REGISTRY_HTTP_PORT:8090}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://${MONGO_USER:${MONGO_INITDB_ROOT_USERNAME:dodash}}:${MONGO_PASSWORD:${MONGO_INITDB_ROOT_PASSWORD:Mongo@2025}}@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/${MONGO_DB:${MONGO_DB_REGISTRY:dodash_registry}}?authSource=${MONGO_AUTH_DB:admin}}
