# --- PROD profile overrides ---
server:
  port: ${REGISTRY_HTTP_PORT:8090}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:mongo}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:dodash_registry}
      username: ${MONGO_USER:registry}
      password: ${MONGO_PASSWORD:Mongo@2025}
      authentication-database: ${MONGO_AUTH_DB:admin}