# --- DEV profile overrides ---
server:
  port: ${REGISTRY_HTTP_PORT:8090}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dodash_registry
      username: dodo25
      password: dodo25
      authentication-database: admin
