# --- DEV profile overrides ---
server:
  port: 8090

spring:
  data:
    mongodb:
      username: dodo25
      password: dodo25
      host: localhost
      port: 27017
      database: dodash_registry
      authentication-database: admin
