# --- DEV profile overrides ---
server:
  port: ${REGISTRY_HTTP_PORT:8090}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dodash_registry
      username: dodash_mg
      password: Dodash#@2025
      authentication-database: dodash_registry
