# --- PROD profile overrides ---
server:
  port: ${REGISTRY_HTTP_PORT:8090}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://${MONGO_USER:registry}:${MONGO_PASSWORD:Mongo@2025}@${MONGO_HOST:mongo}:${MONGO_PORT:27017}/${MONGO_DB:dodash_registry}?authSource=${MONGO_AUTH_DB:admin}}
