# --- PROD profile overrides ---
server:
  port: ${REGISTRY_HTTP_PORT:8090}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:mongodb}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:dodash_registry}
      username: ${MONGO_USER:MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_PASSWORD:MONGO_INITDB_ROOT_PASSWORD}
      authentication-database: ${MONGO_AUTH_DB:admin}