server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: dodash-x-registry-service
          uri: lb://DODASH-X-REGISTRY-SERVICE
          predicates:
            - Path=/api/v1/registry/**
#        - id: order-service
#          uri: lb:http://ORDER-SERVICE
#          predicates:
#            - Path=/api/v1/orders/**
#        - id: order-lines-service
#          uri: lb:http://ORDER-SERVICE
#          predicates:
#            - Path=/api/v1/order-lines/**
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: product-service-stock
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/stocks/**
        - id: product-service-mvt-stock
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/stock-movements/**
        - id: purchase-service
          uri: lb:http://PURCHASE-SERVICE
          predicates:
            - Path=/api/v1/purchases/**
        - id: purchase-lines-service
          uri: lb://PURCHASE-SERVICE
          predicates:
            - Path=/api/v1/purchase-lines/**
        - id: sale-service
          uri: lb://SALE-SERVICE
          predicates:
            - Path=/api/v1/sales/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
        - id: cloud-storage-service
          uri: lb://CLOUD-STORAGE-SERVICE
          predicates:
            - Path=/api/v1/files/**, /api/v1/upload/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8088"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Origin
              - Content-Type
              - Accept
              - Authorization
              - X-Requested-With
            exposedHeaders:
              - Authorization
              - X-Total-Count
              - Location
            allowCredentials: true
