# --- DEV profile overrides ---
server:
  port: 8040

spring:
  data:
    mongodb:
      username: dodo25
      password: dodo25
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:19092

  mail:
    host: localhost
    port: 11025           # <- MailDev SMTP exposé
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false     # <- pas d’auth sur MailDev
          starttls:
            enable: false # <- pas de TLS sur MailDev
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
