# --- DEV profile overrides ---
server:
  port: 8040

spring:
  data:
    mongodb:
      username: dodo25
      password: dodo25
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092

  mail:
    host: localhost
    port: 1025
    username: alibou
    password: alibou
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
