# --- PROD profile overrides ---
server:
  port: ${NOTIF_PORT:8040}

spring:
  data:
    mongodb:
      username: ${MONGO_USER:notification}
      password: ${MONGO_PASSWORD:changeMe!}
      host: ${MONGO_HOST:mongo}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:notification}
      authentication-database: ${MONGO_AUTH_DB:admin}

  kafka:
    consumer:
      # En prod, pointer vers le cluster Kafka (service docker ou externe)
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          trust: "${MAIL_SMTP_TRUST:*}"
        auth: ${MAIL_SMTP_AUTH:true}
        starttls:
          enabled: ${MAIL_STARTTLS_ENABLED:true}
        connectiontimeout: ${MAIL_CONNECTION_TIMEOUT:5000}
        timeout: ${MAIL_TIMEOUT:3000}
        writetimeout: ${MAIL_WRITE_TIMEOUT:5000}
