# --- PROD profile overrides ---
server:
  port: 8050

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # Prefer env-driven values in production; defaults below are sane fallbacks
    url: ${PRODUCT_DB_URL:jdbc:postgresql://postgres:5432/product_server}
    username: ${PRODUCT_DB_USER:product}
    password: ${PRODUCT_DB_PASSWORD:changeMe!}
