# --- Shared defaults served by Config Server for ALL profiles ---
server:
  servlet:
    context-path: /api/v1

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

# Application custom settings
application:
  config:
    # Can be overridden via env on clients if needed
    registry-url: ${REGISTRY_URL:http://localhost:8222/api/v1/registry}
    cloud-storage-url: ${CLOUD_STORAGE_URL:http://localhost:8222/api/v1/upload}

# Expose actuator endpoints useful for config refresh
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
