# --- DEV profile overrides ---
server:
  port: 8050

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product_server
    username: dodo25
    password: dodo25
