# --- DEV profile overrides ---
server:
  port: 8050

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15433/product_server
    username: dodash_pg
    password: Dodash#@2025
