# --- PROD profile overrides ---
server:
  port: ${PURCHASE_PORT:8070}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PURCHASE_DB_URL:jdbc:postgresql://postgres:5432/purchase_server}
    username: ${PURCHASE_DB_USER:purchase}
    password: ${PURCHASE_DB_PASSWORD:changeMe!}

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

application:
  config:
    # En prod, tu peux pointer par défaut sur la gateway docker (override possible via ENV)
    product-url: ${PRODUCT_URL:http://gateway-service:8222/api/v1/products}
