# --- DEV profile overrides ---
server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/purchase_server
    username: postgres
    password: postgres

  kafka:
    producer:
      bootstrap-servers: localhost:19092
