# --- Shared defaults served by Config Server for ALL profiles ---
server:
  servlet:
    context-path: /api/v1

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      # bootstrap-servers défini par profil (dev/prod)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: saleConfirmation:com.dodo.dodashx.kafka.SaleConfirmation

  cache:
    type: caffeine
    caches:
      product-name-cache:
        spec: maximumSize=1000,expireAfterWrite=2h
      unit-cache:
        spec: maximumSize=500,expireAfterWrite=6h
      category-cache:
        spec: maximumSize=300,expireAfterWrite=12h

application:
  config:
    # Overridable via ENV ; défauts utiles en dev local
    product-url: ${PRODUCT_URL:http://localhost:8222/api/v1/products}
    registry-url: ${REGISTRY_URL:http://localhost:8222/api/v1/registry}

feign:
  client:
    config:
      default:
        errorDecoder: com.dodo.dodashx.config.FeignClientErrorDecoder

logging:
  level:
    com.dodo.dodashx: INFO
    com.dodo.dodashx.CacheMonitorService: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
