# --- DEV profile overrides ---
server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sale_server
    username: postgres
    password: postgres

  kafka:
    producer:
      bootstrap-servers: localhost:9092
