# --- PROD profile overrides ---
server:
  port: ${SALE_PORT:8085}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SALE_DB_URL:jdbc:postgresql://postgres:5432/sale_server}
    username: ${SALE_DB_USER:sale}
    password: ${SALE_DB_PASSWORD:changeMe!}

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

application:
  config:
    # En prod, pointer par défaut vers la gateway du cluster (override possible via ENV)
    product-url: ${PRODUCT_URL:http://gateway-service:8222/api/v1/products}
    registry-url: ${REGISTRY_URL:http://gateway-service:8222/api/v1/registry}
