# --- DEV profile overrides ---
server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/sale_server
    username: dodo25
    password: dodo25

  kafka:
    producer:
      bootstrap-servers: localhost:9092
